const Sequelize = require("sequelize");
const sequelize = require("../database/database");
const InstructorVariableData = sequelize.define("InstructorVariableData",{
    register_type:{
        type:Sequelize.STRING(2),
        allowNull:false,
        defaultValue:'50'
    },
    school_inep_id_fk:{
        type:Sequelize.STRING(8),
        allowNull:false
    },
    inep_id:{
        type:Sequelize.STRING(12),
        defaultValue:null
    },
    id:{
        primaryKey:true,
        type:Sequelize.INTEGER,
        allowNull:false,
        autoIncrement:true
    },
    scholarity:{
        allowNull:false,
        type:Sequelize.SMALLINT.length(6)
    },
    high_education_situation_1:{
        defaultValue:null,
        type:Sequelize.SMALLINT.length(6)
    },
    high_education_formation_1:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    high_education_course_code_1_fk:{
        type:Sequelize.STRING(6),
        defaultValue:null,
        references:{
            model:'edcenso_course_of_higher_education',
            key:'id'
        }
    },
    high_education_initial_year_1:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_final_year_1:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_institution_code_1_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_ies',
            key:'id'
        }
    },
    high_education_situation_2:{
        defaultValue:null,
        type:Sequelize.SMALLINT.length(6)
    },
    high_education_formation_2:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    high_education_course_code_2_fk:{
        type:Sequelize.STRING(6),
        defaultValue:null,
        references:{
            model:'edcenso_course_of_higher_education',
            key:'id'
        }
    },
    high_education_initial_year_2:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_final_year_2:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_institution_code_2_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_ies',
            key:'id'
        }
    },
    high_education_situation_3:{
        defaultValue:null,
        type:Sequelize.SMALLINT.length(6)
    },
    high_education_formation_3:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    high_education_course_code_3_fk:{
        type:Sequelize.STRING(6),
        defaultValue:null,
        references:{
            model:'edcenso_course_of_higher_education',
            key:'id'
        }
    },
    high_education_initial_year_3:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_final_year_3:{
        type:Sequelize.STRING(4),
        defaultValue:null
    },
    high_education_institution_code_3_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_ies',
            key:'id'
        }
    },
    post_graduation_specialization:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    post_graduation_master:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    post_graduation_doctorate:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    post_graduation_none:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    },
    other_courses_nursery:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_pre_school:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_basic_education_initial_years:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_basic_education_final_years:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_high_school:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_education_of_youth_and_adults:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_special_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_native_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_field_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_environment_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_human_rights_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_sexual_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_child_and_teenage_rights:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_ethnic_education:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_other:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    other_courses_none:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    hash:{
        type:Sequelize.BIGINT.length(20),
        defaultValue:null
    }
},{tableName:"instructor_variable_data",timestamps:false});
module.exports = InstructorVariableData;