const Sequelize = require("sequelize");
const sequelize = require("../database/database");
const InstructorTeachingData = sequelize.define("InstructorTeachingData",{
    register_type:{
        type:Sequelize.STRING(2),
        allowNull:false,
        defaultValue:'51'
    },
    school_inep_id_fk:{
        type:Sequelize.STRING(8),
        allowNull:false,
        references:{
            model:'school_identification',
            key:'inep_id'
        }
    },
    instructor_inep_id:{
        type:Sequelize.STRING(12),
        defaultValue:null,
    },
    instructor_fk:{
        type:Sequelize.INTEGER,
        allowNull:null,
        references:{
            model:'instructor_identification',
            key:'id'
        }
    },
    classroom_inep_id:{
        type:Sequelize.STRING(8),
        defaultValue:null
    },
    classroom_id_fk:{
        type:Sequelize.INTEGER,
        allowNull:null,
        references:{
            model:'classroom',
            key:'id'
        }
    },
    role:{
        type:Sequelize.SMALLINT.length(6),
        allowNull:false
    },
    contract_type:{
        type:Sequelize.SMALLINT.length(6),
        defaultValue:null
    },
    discipline_1_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_2_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_3_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_4_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_5_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_6_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_7_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_8_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_9_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_10_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_11_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_12_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    discipline_13_fk:{
        type:Sequelize.INTEGER.length(11),
        defaultValue:null,
        references:{
            model:'edcenso_discipline',
            key:'id'
        }
    },
    id:{
        primaryKey:true,
        type:Sequelize.INTEGER(11),
        allowNull:false,
        autoIncrement:true
    },
    hash:{
        type:Sequelize.BIGINT.length(20),
        defaultValue:null
    },
    hash_instructor:{
        type:Sequelize.BIGINT.length(20),
        defaultValue:null
    },
    hash_classroom:{
        type:Sequelize.BIGINT.length(20),
        defaultValue:null
    }
},{tableName:"instructor_school",timestamps:false});
module.exports = InstructorTeachingData;