const Sequelize = require("sequelize");
const sequelize = require("../database/database");
const InstructorIdentification = sequelize.define("InstructorIdentification",{
    register_type:{
        type:Sequelize.STRING(2),
        allowNull:false,
        defaultValue:'30'
    },
    school_inep_id_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'school_identification',
            key:'inep_id'
        }
    },
    id:{
        primaryKey:true,
        type:Sequelize.INTEGER(11),
        allowNull:false,
        unique:true
    },
    acronym:{
        allowNull:false,
        type:Sequelize.STRING(2)
    },
    name:{
        allowNull:false,
        type:Sequelize.STRING(100)
    },
    email:{
        defaultValue:null,
        type:Sequelize.STRING(100)
    },
    nis:{
        defaultValue:null,
        type:Sequelize.STRING(11)
    },
    birthday_date:{
        allowNull:false,
        type:Sequelize.STRING(10)
    },
    sex:{
        allowNull:false,
        type:Sequelize.SMALLINT.length(6)
    },
    color_race:{
        allowNull:false,
        type:Sequelize.SMALLINT.length(6)
    },
    filiation:{
        defaultValue:'1',
        type:Sequelize.TINYINT.length(1)
    },
    filiation_1:{
        defaultValue:null,
        type:Sequelize.STRING(100) 
    },
    filiation_2:{
        defaultValue:null,
        type:Sequelize.STRING(100)
    },
    nationality:{
        type:Sequelize.SMALLINT.length(6),
        allowNull:false
    },
    edcenso_nation_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_nation',
            key:'id'
        }
    },
    edcenso_uf_fk:{
        type:Sequelize.INTEGER,
        defaultValue:null,
        references:{
            model:'edcenso_uf',
            key:'id'
        }
    },
    edcenso_city_fk:{
        type:Sequelize.INTEGER,
        defaultValue:null,
        references:{
            model:'edcenso_city',
            key:'id'
        }
    },
    deficiency:{
        type:Sequelize.TINYINT.length(1),
        allowNull:false
    },
    deficiency_type_blindness:{
        type:Sequelize.TINYINT.length(1),
        defaultValue:null
    }
},{tableName:"instructor_identification",timestamps:false});
module.exports = InstructorIdentification;