const Sequelize = require("sequelize");
const sequelize = require("../database/database");
const InstructorDocumentsAndAddress = sequelize.define("InstructorDocumentsAndAddress",{
    register_type:{
        type:Sequelize.STRING(2),
        allowNull:false,
        defaultValue:"40"
    },
    school_inep_id_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'school_identification',
            key:'inep_id'
        }
    },
    inep_id:{
        type:Sequelize.STRING(12),
        defaultValue:null
    },
    id:{
        primaryKey:true,
        type:Sequelize.INTEGER(11),
        allowNull:false,
        autoIncrement:true
    },
    cpf:{
        defaultValue:null,
        type:Sequelize.STRING(11)
    },
    area_of_residence:{
        defaultValue:null,
        type:Sequelize.SMALLINT.length(6)
    },
    cep:{
        type:Sequelize.STRING(8),
        defaultValue:null
    },
    address:{
        type:Sequelize.STRING(100),
        defaultValue:null
    },
    address_number:{
        type:Sequelize.STRING(10),
        defaultValue:null
    },
    complement:{
        type:Sequelize.STRING(20),
        defaultValue:null
    },
    neighborhood:{
        type:Sequelize.STRING(50),
        defaultValue:null
    },
    edcenso_uf_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_uf',
            key:'id'
        }
    },
    edcenso_city_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_city',
            key:'id'
        }
    },
    hash:{
        type:Sequelize.BIGINT.length(20),
        defaultValue:null
    },
    diff_location:{
        type:Sequelize.SMALLINT.length(4),
        defaultValue:null
    }
},{tableName:"instructor_documents_and_address",timestamps:false});
module.exports = InstructorDocumentsAndAddress;