const Sequelize = require("sequelize");
const sequelize = require("../database/database");

const schoolStructure = sequelize.define("school_structure",{
    register_type:{
        allowNull:false,
        type:Sequelize.STRING
    },
    school_inep_id_fk:{
        type:Sequelize.STRING,
        references:{
            model:'school_identification',
            key:'inep_id'
        },
        primaryKey:true
    },
    operation_location_building:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_temple:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_businness_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_instructor_house:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_other_school_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_barracks:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_socioeducative_unity:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_prison_unity:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    operation_location_other:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    building_occupation_situation:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    shared_building_with_school:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    shared_school_inep_id_1:{
        type:Sequelize.STRING,
        allowNull:false
    },
    shared_school_inep_id_2:{
        type:Sequelize.STRING,
        allowNull:false
    },
    shared_school_inep_id_3:{
        type:Sequelize.STRING,
        allowNull:false
    },
    shared_school_inep_id_4:{
        type:Sequelize.STRING,
        allowNull:false
    },
    shared_school_inep_id_5:{
        type:Sequelize.STRING,
        allowNull:false
    },
    shared_school_inep_id_6:{
        type:Sequelize.STRING,
        allowNull:false
    },
    consumed_water_type:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    water_supply_public:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    water_supply_artesian_well:{
        type:Sequelize.INTEGER,
        allowNull:false,
    },
    water_supply_well:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    water_supply_river:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    water_supply_inexistent:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    energy_supply_public:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    energy_supply_generator:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    energy_supply_other:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    energy_supply_inexistent:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sewage_public:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sewage_fossa:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sewage_inexistent:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_collect:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_burn:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_throw_away:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_recycle:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_bury:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    garbage_destination_other:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_principal_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_instructors_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_secretary_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_info_lab:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_science_lab:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_aee_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_indoor_sports_court:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_outdoor_sports_court:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_kitchen:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_library:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_reading_room:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_playground:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_nursery:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_outside_bathroom:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_inside_bathroom:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_child_bathroom:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_prysical_disability_bathroom:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_physical_disability_support:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_bathroom_with_shower:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_refectory:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_storeroom:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    adependencies_warehouse:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_auditorium:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_covered_patio:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_uncovered_patio:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_student_accomodation:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_instructor_accomodation:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_green_area:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_laundry:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    dependencies_none:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    classroom_count:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    used_classroom_count:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_tv:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_vcr:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_dvd:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_satellite_dish:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_copier:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_overhead_projector:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_printer:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_stereo_system:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_data_show:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_fax:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_camera:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_computer:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    equipments_multifunctional_printer:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    administrative_computers_count:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    student_computers_count:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    internet_access:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    bandwidth:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    employees_count:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    feeding:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    aaee:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    complementary_activities:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    modalities_regular:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    modalities_especial:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    modalities_eja:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    modalities_professional:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    basic_education_cycle_organized:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    different_location:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sociocultural_didactic_material_none:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sociocultural_didactic_material_quilombola:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    sociocultural_didactic_material_native:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    native_education:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    native_education_language_native:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    native_education_language_portuguese:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    edcenso_native_languages_fk:{
        type:Sequelize.INTEGER,
        references:{
            model:'edcenso_native_languages',
            key:'id'
        }
    },
    brazil_literate:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    open_weekend:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    pedagogical_formation_by_alternance:{
        type:Sequelize.INTEGER,
        allowNull:false
    },


},{tableName:"school_structure",timestamps:false});
module.exports = schoolStructure;