const Sequelize = require("sequelize");
const sequelize = require("../database/database");
const StudentIdentification = sequelize.define("StudentIdentification",{
    register_type:{
        allowNull:false,
        type:Sequelize.STRING(2)
    },
    school_inep_id_fk:{
        type:Sequelize.STRING,
        references:{
            model:'school_identification',
            key:'inep_id'
        }
    },
    inep_id:{
        type:Sequelize.STRING,
        allowNull:false
    },
    id:{
        primaryKey:true,
        type:Sequelize.INTEGER,
        allowNull:false,
        autoIncrement:true
    },
    name:{
        type:Sequelize.STRING,
        allowNull:false
    },
    birthday:{
        type:Sequelize.STRING,
        allowNull:false
    },
    sex:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    color_race:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    filiation:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    filiation_1:{
        type:Sequelize.STRING,
        allowNull:false
    },
    filiation_2:{
        type:Sequelize.STRING,
        allowNull:false
    },
    nationality:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    edcenso_nation_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_nation',
            key:'id'
        }
    },
    edcenso_uf_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_uf',
            key:'id'
        }
    },
    edcenso_city_fk:{
        type:Sequelize.INTEGER,
        allowNull:false,
        references:{
            model:'edcenso_city',
            key:'id'
        }
    },
    deficiency:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_blindness:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_low_vision:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_deafness:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_disability_hearing:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_deafblindness:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_phisical_disability:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_intelectual_disability:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_multiple_disabilities:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_autism:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_aspenger_syndrome:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_rett_syndrome:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_childhood_disintegrative_disorder:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    deficiency_type_gifted:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_aid_lector:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_aid_transcription:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_interpreter_guide:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_interpreter_libras:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_lip_reading:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_zoomed_test_16:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_zoomed_test_20:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_zoomed_test_24:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_braille_test:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    resource_none:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    send_year:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    last_change:{
        type:Sequelize.STRING,
        allowNull:false
    },
    responsable:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    responsable_name:{
        type:Sequelize.STRING,
        allowNull:false
    },
    responsable_rg:{
        type:Sequelize.STRING,
        allowNull:false
    },
    responsable_cpf:{
        type:Sequelize.STRING,
        allowNull:false
    },
    responsable_scholarity:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    responsable_job:{
        type:Sequelize.STRING,
        allowNull:false
    },
    bf_participator:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    food_restrictions:{
        type:Sequelize.STRING,
        allowNull:false
    },
    responsable_telephone:{
        type:Sequelize.STRING,
        allowNull:false
    },
    tag_id:{
        type:Sequelize.STRING,
        allowNull:false
    },
    fkid:{
        type:Sequelize.STRING,
        allowNull:false
    }
},{tableName:"student_identification",timestamps:false});
module.exports = StudentIdentification;